from .base import *  # noqa: F403

DEBUG = False
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31_536_000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SPECTACULAR_SETTINGS['SERVE_INCLUDE_SCHEMA'] = False  # noqa: F405
